# Generated by Django 4.2.13 on 2024-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="title",
            new_name="symbol",
        ),
    ]
